### ISSUE TITLE
Crear componente de mapa de calor en tiempo real

### ISSUE THREAD

**Issue by damianfanaro** [igrowker/i003-altour-front#1]
Desarrollar el componente 'MapaCalorComponent' que muestre un mapa de calor interactivo que refleje en tiempo real las zonas más saturadas de turistas. Este componente debe estar conectado a las APIs de HERE Maps y OpenStreetMap para obtener los datos y mostrar visualmente las áreas congestionadas.

**Comment by jomuarribas** [comment]
Se desestima la funcionalidad a tiempo real ya que no tenemos posibilidad de rescatar esos datos. Como alternativa se propone utilizar la api de google maps places para recuperar sus datos de afluencia de gente. No son a tiempo real pero si muy actuales.

**Comment by jomuarribas** [comment]
Componente terminado y funcionando perfectamente.
